// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMUzIfGk2LfkvJAYKV7jPVTYO7zH8PDgQ',
    appId: '1:691540735642:web:bbd26cd4c6d59691ad9123',
    messagingSenderId: '691540735642',
    projectId: 'sleep-pad-7a310',
    authDomain: 'sleep-pad-7a310.firebaseapp.com',
    storageBucket: 'sleep-pad-7a310.appspot.com',
    measurementId: 'G-2Q2G9676RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-rbG2E-aKv0-LeqS6kfGjGj9h0sWh9Y',
    appId: '1:691540735642:android:3e935522451acd73ad9123',
    messagingSenderId: '691540735642',
    projectId: 'sleep-pad-7a310',
    storageBucket: 'sleep-pad-7a310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiCZTpQ58K33xaeNMQHsWEPkMkEcstk2c',
    appId: '1:691540735642:ios:d6d9e1c737d62510ad9123',
    messagingSenderId: '691540735642',
    projectId: 'sleep-pad-7a310',
    storageBucket: 'sleep-pad-7a310.appspot.com',
    iosClientId: '691540735642-hri26g1vltch9459jsd042ktnqtr7arh.apps.googleusercontent.com',
    iosBundleId: 'com.sleepkraft.sleepPad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiCZTpQ58K33xaeNMQHsWEPkMkEcstk2c',
    appId: '1:691540735642:ios:d6d9e1c737d62510ad9123',
    messagingSenderId: '691540735642',
    projectId: 'sleep-pad-7a310',
    storageBucket: 'sleep-pad-7a310.appspot.com',
    iosClientId: '691540735642-hri26g1vltch9459jsd042ktnqtr7arh.apps.googleusercontent.com',
    iosBundleId: 'com.sleepkraft.sleepPad',
  );
}
